parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): 'mysql://paola:root@db:3306/lana'

doctrine:
    dbal:
        dbname:               lana
        host:                 db
        port:                 3306
        user:                 openhanditour
        password:             openhanditour
        driver:               pdo_mysql
        server_version:       '5.7'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            numeric_functions:
                acos: App\Service\Dql\Acos
                sin: App\Service\Dql\Sin
                cos: App\Service\Dql\Cos
                pi: App\Service\Dql\Pi
