version: '3'

services:
  web:
    build: docker/dev
    volumes:
      - .:/openhanditour:delegated
      - ~/.ssh:/openhanditour/.ssh
      - ~/.composer:/openhanditour/.composer
    ports:
      - 81:80
    depends_on:
      - db

  db:
    image: mysql
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: lana

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sf4_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8080:80
    links:
      - db
